// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArkhpGmzLFa-FSR5OouXk6Im-agjlIgYo',
    appId: '1:975205278869:android:0b2bdcebc2c5198daee79c',
    messagingSenderId: '975205278869',
    projectId: 'my-spots-1',
    storageBucket: 'my-spots-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaefsr8Ek2Y_6yY8B6urJa2VTcmMMB2xU',
    appId: '1:975205278869:ios:efa061df7709b592aee79c',
    messagingSenderId: '975205278869',
    projectId: 'my-spots-1',
    storageBucket: 'my-spots-1.appspot.com',
    androidClientId:
        '975205278869-5687cjebml84qfh8v62aqk3p047igr57.apps.googleusercontent.com',
    iosClientId:
        '975205278869-qujf76h5niush72fc2o9ansv5qifr59s.apps.googleusercontent.com',
    iosBundleId: 'com.myspots.myspots',
  );
}
